version: '2'
services:
  revp:
    image: nginx:latest
    volumes:
      - "/root/docker-registry/nginx-root:/usr/share/nginx/html:ro"
      - "/root/docker-registry/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/root/docker-registry/certs:/usr/share/certs:ro"
      - "/root/docker-registry/auth/htpasswd:/etc/nginx/.htpasswd:ro"
    ports:
      # - "80:80"
      - "443:443"
    depends_on:
      - reg
    links:
      - reg
#    networks:
#      static-network:
#        ipv4_address: 172.19.0.2
  reg:
    image: registry
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - "/root/docker-registry/reg-data:/var/lib/registry:rw"
      - "/root/docker-registry/config.yml:/etc/docker/registry/config.yml:ro"
#    networks:
#      static-network:
#        ipv4_address: 172.19.0.3  
  # docker-registry-host-web-ui:
  #   image: joxit/docker-registry-ui
  #   environment:
  #     #URL: "http://docker-registry.contegris.com"
  #     NGINX_PROXY_PASS_URL: "http://docker-registry.contegris.com:5000"
  #     REGISTRY_TITLE: "Contegris Docker REGISTRY"
  #     #SINGLE_REGISTRY: true
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - reg
  #   links:
  #     - reg

  web-ui:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry.contegris.com
      ENV_DOCKER_REGISTRY_PORT: 443
    ports:
      - 8080:80
      - 8443:443
#    volumes:
#      - "/root/docker-registry/apache2/apache2.conf:/etc/apache2/apache2.conf:ro"
#      - "/root/docker-registry/apache2/site-enabled:/etc/apache2/apache2.conf:ro"
    depends_on:
      - reg
    links:
      - reg
#    networks:
#      static-network:
#        ipv4_address: 172.19.0.4

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.19.0.0/24